# ─── Borrow Service specific config ─────────────

server.port=8083
spring.application.name=borrow-service

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/borrows_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Borrow specific
borrow.fine-per-day=5.0
borrow.max-borrow-days=30
borrow.reminder-days-before-due=3
